language: minimal

services: docker 

env:
  - DOCKER_COMPOSE_VERSION=1.25.4

before_install:
  - echo "nothing to do before_install"

# Pre-testing installs
install:
  - echo "-------- install start --------"
  # - docker-compose -f udacity-c3-deployment/docker/docker-compose-build.yaml build --parallel
  - echo "\n\n\n"
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config
  - mkdir ${HOME}/.aws
  - echo "$KUBE_AWS_CREDENTIALS" | base64 --decode > ${HOME}/.aws/credentials
  - echo "-------- install complete --------"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - echo "-------- script start --------"
  - docker --version # print the version for logging
  - echo "\n\n\n"
  - kubectl get pods
  - echo "\n\n\n"
  - echo "-------- script complete --------"

after_success:
  - echo "-------- after_success start --------"
  # - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker push padraighow/udacity-restapi-feed:latest
  # - docker push padraighow/udacity-restapi-user:latest
  # - docker push padraighow/udacity-frontend:local
  # - docker push padraighow/reverseproxy
  - echo "-------- after_success end --------"
